### ISSUE TITLE
Image importing doesn't work

### ISSUE THREAD

**Issue by langmore** [columbia-applied-data-science/rosetta#16]
When `docx` is imported, `docx` imports `Image` (with a capital `I`).  This doesn't work.  It should (I believe) `import image` (with lower case).  This works.  I have `image` installed on my machine.  I have done both `pip install image` and `pip install Image`, but only `import image` can work.  For some reason, the version of `docx` being used says `import Image`, which is absolutely screwball since a Python module is _never_ named with capital letters.  I recommend finding a version of `docx` that works and then putting that in `requirements.txt` (also, there should be some way to enforce these requirements...not sure if that is set up.

Traceback below.

``` python
ImportError: Failed to import test module: test_text
Traceback (most recent call last):
  File "/Users/langmore/anaconda/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/Users/langmore/anaconda/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/Users/langmore/lib/rosetta/rosetta/tests/test_text.py", line 13, in <module>
    from rosetta.text import text_processors, vw_helpers, nlp, converters
  File "rosetta/text/converters.py", line 7, in <module>
    from docx import opendocx, getdocumenttext
  File "/Users/langmore/anaconda/lib/python2.7/site-packages/docx.py", line 23, in <module>
    import Image
  File "/Users/langmore/anaconda/lib/python2.7/site-packages/PIL/Image.py", line 53, in <module>
    from PIL import _imaging as core
ImportError: dlopen(/Users/langmore/anaconda/lib/python2.7/site-packages/PIL/_imaging.so, 2): Library not loaded: libjpeg.8.dylib
  Referenced from: /Users/langmore/anaconda/lib/python2.7/site-packages/PIL/_imaging.so
  Reason: image not found
```

**Comment by gerrywastaken** [comment]
For me all I needed to do was "sudo pip install --upgrade pillow". It uninstalled Pillow 2.3.2 and then reinstalled what seems to be the exact same version. Things then worked.
